url: http://disposablefilm.com/

# other site variables and configs
exclude:
- Gemfile
- Gemfile.lock
- lib
- vendor
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  bundles:
    - 'shared.css'
    - 'shared.js'
    - 'application.css'
    - 'application.js'
  compress:
    css: sass
    js: uglifier
  cachebust: soft
  gzip:
  - text/css
  - application/javascript
show_ads: false

# Outputting
permalink: /:title.html

prose:
  siteurl: 'http://disposablefilm.com/'

  ignore:
    - _config_production.yml
    - _config.yml
    - /_layouts
    - /_site
    - /_includes
    - /_plugins
    - /blog
    - /events
    - /fonts
    - /lcs
    - /search
    - /watch
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md
    - Rakefile
    - favicon.ico
    - index.haml
    - process.txt
    - vote_process.php

  metadata:
    _posts:
      - name: "layout"
        field:
          element: select
          label: "Is this a single post or a collection post?"
          help: "Do this with gusto!"
          options:
            - name: "Single Post"
              value: "singleton"
            - name: "Collection"
              value: "collection"
