url: http://disposablefilm.com/

# other site variables and configs
exclude:
- Gemfile
- Gemfile.lock
- lib
- vendor
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  bundles:
    - 'shared.css'
    - 'shared.js'
    - 'application.css'
    - 'application.js'
  compress:
    css: sass
    js: uglifier
  cachebust: soft
  gzip:
  - text/css
  - application/javascript
show_ads: false

# Outputting
permalink: /:title.html

prose:
  rooturl: '_posts'

  #siteurl: 'http://prose.github.io/starter/'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  #media: 'media'
  #ignore:
  #  - index.md
  #  - _config.yml
  #  - /_layouts
  #  - /_includes

  metadata:
    _posts:
      - name: "layout"
        field:
          element: select
          label: "Is this a single post or a collection post?"
          help: "Do this with gusto!"
          options:
            - name: "Single Post",
              value: "singleton"
            - name: "Collection",
              value: "collection"
      - name: "title"
        field:
          element: text
          type: text
          label: "Post or Collection Title"
      - name: "categories"
        field:
          element: multiselect
          label: "Show this post on the following pages:"
          help: "Do this with gusto!"
          options:
            - name: "Homepage",
              value: "home"
            - name: "Watch Page",
              value: "watch"
            - name: "Event Page",
              value: "events"
            - name: "Blog Page",
              value: "blog"

#image: posts/dff-2015-banner.jpg
#thumb: posts/thumbs/dff-2015-banner.jpg
#relatedthumb: posts/thumbs/dff-2015-banner.jpg
#blurb: Check out the 2015 Disposable Film Festival Winners!
