url: http://disposablefilm.com/

# other site variables and configs
exclude:
- Gemfile
- Gemfile.lock
- lib
- vendor
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  bundles:
    - 'shared.css'
    - 'shared.js'
    - 'application.css'
    - 'application.js'
  compress:
    css: sass
    js: uglifier
  cachebust: soft
  gzip:
  - text/css
  - application/javascript
show_ads: false

# Outputting
permalink: /:title.html

prose:
  siteurl: 'http://disposablefilm.com/'

  ignore:
    - _config_production.yml
    - _config.yml
    - /_layouts
    - /_site
    - /_includes
    - /_plugins
    - /blog
    - /events
    - /fonts
    - /lcs
    - /search
    - /watch
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md
    - Rakefile
    - favicon.ico
    - index.haml
    - process.txt
    - vote_process.php

  metadata:
    _posts:
      - name: "layout"
        field:
          element: select
          label: "Is this a single post or a collection post?"
          help: "Do this with gusto!"
          options:
            - name: "Single Post"
              value: "singleton"
            - name: "Collection"
              value: "collection"
      - name: "title"
        field:
          element: "text"
          label: "Post or Collection Title"
          default: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Show this post on the following pages:"
          help: "Do this with gusto!"
          options:
            - name: "Homepage"
              value: "home"
            - name: "Watch Page"
              value: "watch"
            - name: "Event Page"
              value: "events"
            - name: "Blog Page"
              value: "blog"
      - name: "tags"
        field:
          element: "textarea"
          label: "Tags"
          default: ""
      - name: "video"
        field:
          element: "text"
          label: "Video"
          help: "Path to video on Vimeo or YouTube. Format is: //player.vimeo.com/video/106526309 or https://www.youtube.com/embed/35tBYFUMwzw?list=PLqHxwRtSQAmKqhstdgfvirrcAuUa-EDww"
      - name: "image"
        field:
          element: "text"
          label: "Marquee Image"
          help: "Path to 750x300 image. Images need to be placed in _assets/images/posts/<filename>"
          placeholder: "posts/<filename>"
      - name: "thumb"
        field:
          element: "text"
          label: "Thumbnail Image"
          help: "Path to 220x100 image. Images need to be placed in _assets/images/posts/thumbs/<filename>"
          placeholder: "posts/thumbs/<filename>"
      - name: "relatedthumb"
        field:
          element: "text"
          label: "Thumbnail Image (Related Content)"
          help: "Path to 110x50 image. Images need to be placed in _assets/images/posts/thumbs/<filename>"
          placeholder: "posts/thumbs/<filename>"
      - name: "blurb"
        field:
          element: "textarea"
          label: "Short blurb displayed when this post is part of a collection."
          default: ""
